# This is a basic workflow to help you get started with Actions

name: PreTeXt Processing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install xsltproc and LaTeX
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xsltproc
        sudo apt-get install texlive-latex-base
        sudo apt-get install texlive-fonts-recommended
        sudo apt-get install texlive-fonts-extra
        
    - name: Clone PreTeXt
      run: |
        git clone https://github.com/rbeezer/mathbook.git
        cd mathbook
        git checkout dev
        cd ..
        
    - name: Create Output Directory
      run: mkdir public
    
    - name: Process HTML
      run: xsltproc -o public/quickstart.html ./mathbook/xsl/pretext-html.xsl quickstart.xml
    
    - name: Process LaTeX
      run: | 
        xsltproc -o public/quick.tex ./mathbook/xsl/pretext-latex.xsl quickstart.xml
        pdflatex -output-directory public quick.tex

    - uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: public/
        GH_PAT: ${{ secrets.GH_PAT }}
